[package]
name = "haven-messaging"
version = "0.1.0"
edition = "2024"

[features]
test-support = []

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
haven-common = { path = "../common" }

[dev-dependencies]
tempfile.workspace = true
