[alias]
    t = "test --locked"
    ts = "test --locked -- --nocapture"
    c = "check --locked"
    ci = "test --locked --no-fail-fast"
    tc = "test --locked -p"
    tf = "test --locked --"
    cl = "clippy --locked -- -D warnings"
